services:
  # ----------- Data Base -----------
  auth-db:
    image: postgres:17-alpine
    container_name: auth-db
    restart: unless-stopped
    env_file:
      - ${COMPOSE_ENV_FILE:-.env}
    environment:
      POSTGRES_DB: ${DB_NAME:-auth-db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-auth-db}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - backend

  # ----------- BROKER MESSAGE -----------
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    restart: unless-stopped
    env_file:
      - ${COMPOSE_ENV_FILE:-.env}
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID:-LpQ9m7x4z2t1c8h5v0r3n}
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --list >/dev/null 2>&1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - backend

  # ----------- MICROSERVICES -----------

  auth-service:
    build: ./services/AuthService
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - ${COMPOSE_ENV_FILE:-.env}
      - ./services/AuthService/.env
    environment:
      SRC_BROKER: kafka:29092
      DB_URL: jdbc:postgresql://auth-db:5432/${DB_NAME:-auth-db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${AUTH_SERVICE_PORT:-8080}:8080"
    depends_on:
      auth-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - backend

  api-service:
    build: ./services/API-Service
    container_name: api-service
    restart: unless-stopped
    env_file:
      - ${COMPOSE_ENV_FILE:-.env}
      - ./services/API-Service/.env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8081:8081"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - backend

  bot-service:
    build: ./services/BotService
    container_name: bot-service
    restart: unless-stopped
    env_file:
      - ${COMPOSE_ENV_FILE:-.env}
      - ./services/BotService/.env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - backend

  action-service:
    build: ./services/Action-Service
    container_name: action-service
    restart: unless-stopped
    env_file:
      - ${COMPOSE_ENV_FILE:-.env}
      - ./services/Action-Service/.env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - backend

  db-service:
    build: services/CoreService
    container_name: db-service
    restart: unless-stopped
    env_file:
      - ${COMPOSE_ENV_FILE:-.env}
      - services/CoreService/.env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - backend

  db-postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  handle-service:
    build: ./services/Handle-Service
    container_name: handle-service
    restart: unless-stopped
    env_file:
      - ${COMPOSE_ENV_FILE:-.env}
      - ./services/Handle-Service/.env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - backend

volumes:
  postgres_data:
  auth-db-data:
  kafka-data:

networks:
  backend:
    driver: bridge
